export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const SET_CART_ITEMS = "SET_CART_ITEMS";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const BUY_PRODUCT_PAGE_PRICE = "BUY_PRODUCT_PAGE_PRICE";
